### ISSUE TITLE
Switch not working after upgrade to 0.109

### ISSUE THREAD

**Issue by erikkt** [gkreitz/homeassistant-grohe_sense#1]
The switch to turn on and off water flow is no longer working after upgrade to 0.109.

**Comment by gkreitz** [comment]
My guess is this is just an earlier symptom of #2 - likely your refresh token expired while home assistant was running (soon after you updated to 0.109) and this broke the switch functionality first (and then your whole home assistant when you restarted, per #3). Based on this guess, I'll close this issue.

If this issue persists even when the rest of the component is working, please re-open. If so, it would be tremendously helpful if you could enable debug logging and provide some logs.

**Comment by erikkt** [comment]
SwitchDevice is deprecated, modify GroheSenseGuardValve to extend SwitchEntity
6:29:34 PM – Switch (WARNING)

Logger: homeassistant.components.switch
Source: components/switch/init.py:125
Integration: Switch (documentation, issues)
First occurred: 6:29:34 PM (1 occurrences)
Last logged: 6:29:34 PM

**Comment by erikkt** [comment]
This issue is not due to outdated refresh_token. A newly fetched refresh_token fixed the broken integration and everything else, execpt the switch. Please see log from user Maker2000

**Comment by gkreitz** [comment]
Thanks for following up. Re-opening, will take a look when I have time

**Comment by gkreitz** [comment]
Made an update and now it works again for me, so please give it a try. Thanks for reporting the bug!
