### ISSUE TITLE
grohe sense integration doesn't work after update to core 2021.6.0

### ISSUE THREAD

**Issue by ghost** [gkreitz/homeassistant-grohe_sense#18]
Since update of core to version core-2021.6.0 the grohe sense integration doesn't work anymore. See logs:
Setup failed for grohe_sense: Integration not found.
11:05:56 – (FEHLER) setup.py

I have nothing changed before update. If I check my configuration in the server tab there is the following message:

Konfiguration überprüfen
Überprüfen Sie Ihre Konfiguration, wenn Sie kürzlich Änderungen vorgenommen haben und sicherstellen möchten, dass alle Änderungen gültig sind
Konfiguration fehlerhaft 
KONFIGURATION PRÜFEN
  Component error: grohe_sense - Integration 'grohe_sense' not found.

Folder is still under custom components. I also tried a new refresh token.

Thank you for your help.

Daniel

**Comment by isujosh** [comment]
I had the exact same issue after updating to 2021.6.0. I corrected it by adding a version number to the 'manifest.json' file.

Hope that helps.

**Comment by ghost** [comment]
@isujosh can you please give me an example for the version number?

**Comment by isujosh** [comment]
I just used 1.0.0. Here is my manifest.json file

`{
	"domain": "grohe_sense",
	"name": "Grohe Sense",
	"documentation": "https://github.com/gkreitz/homeassistant-grohe_sense",
	"dependencies": [],
	"requirements": [],
	"codeowners": ["@gkreitz"],
        "version": "1.0.0"
}`

Once included, restart HA

**Comment by ghost** [comment]
Thanks it works again.
