### ISSUE TITLE
Breaks HA after update 

### ISSUE THREAD

**Issue by parhedberg** [gkreitz/homeassistant-grohe_sense#2]
After the latest automatic update for "home assistant raspberry py OS", this plugin breaks the setup.

Raspberry pi boots, and enables samba, but not web interface. Nothing in logs... 

Disabeling it makes it work again.

**Comment by erikkt** [comment]
Same issue here.

**Comment by gkreitz** [comment]
Thanks for reporting this!

Have you tried turning on debug level logging for this component? If you do, my guess is that you'll see a lot of 401 errors relating to token fetching. This is a symptom of the refresh token timing out (they last a couple of months, controlled by Grohe's backend). So try getting a new refresh token and updating the config file with that and see if the problem goes away. If not, I'd very much appreciate logs with debug-level logging turned on.

Adding/merging this (depending on if you already have some logger config) to your `configuration.yaml` turns on debug logging for this component:
```yaml
logger:
  default: error
  logs:
    custom_components.grohe_sense.sensor: debug
```

And of course, it is a bug that this component just retires infinitely with a stale refresh token, thus blocking startup of home assistant. I added a new issue to track that #3 .

**Comment by gkreitz** [comment]
This component should no longer hang home assistant when the refresh token is stale, so closing this ticket. Thanks for reporting the bug!
