### ISSUE TITLE
Process for obtaining Grohe Sense Refresh Token no longer works

### ISSUE THREAD

**Issue by isujosh** [gkreitz/homeassistant-grohe_sense#22]
I've been refreshing my token for Grohe Sense for about 18 months but now I find that the process no longer directs me to the JSON data containing the token but instead gives me a '404' error on the webpage.

Have Grohe changed something around authentication?

**Comment by erikkt** [comment]
I refreshed just a couple of days ago. Worked fine then. Remember incognito mode on your browser.

**Comment by isujosh** [comment]
I've tried it several times now - and in Incognito mode - it's the same result each time when cutting and pasting the 'ondus' redirect URL

https://idp2-apigw.cloud.grohe.com/v3/iot/oidc/token&scope=openid&response_type=code&client_id=iot&state=eaf9cfb3-7c36-423c-8582-xxxxxxxx

It just returns a 404 Page not found. Never had any trouble before retrieving the 'refresh_token'. It's baffling!

**Comment by isujosh** [comment]
Got it now.... but had to use Edge and not Chrome... No real idea why it failed on Chrome though.
