### ISSUE TITLE
More counters

### ISSUE THREAD

**Issue by trsqr** [gkreitz/homeassistant-grohe_sense#6]
Hi,

Thank you for this project! Just took it into use with my Grohe Sense Guard (don't have the small water leak sensors at all).

The app shows consumption per month for the whole year and consumption per day for the current month. Any chance to get those?

Is there a counter for the total consumption since installation? Something that would resemble a traditional water meter. That'd be interesting to have as well.

Maybe you can paste a sample response from the API or is it more complicated than that?

**Comment by gkreitz** [comment]
Glad you liked it, and thanks for submitting feature requests!

I find creating a large number of counters by default from an entity in home assistant pretty annoying (home assistant's internal database and entity model does not really feel like the best place to store time series data). I think a better approach if you want that is likely to push the data to a time series database like influx.
