### ISSUE TITLE
Rename Sense Guard in UI (MY GUARD)

### ISSUE THREAD

**Issue by trsqr** [gkreitz/homeassistant-grohe_sense#7]
I've got one Grohe Sense Guard device. In the HA UI I can see "MY GUARD valve" and "MY GUARD 1 day" for example.

Would it be possible to rename these somehow to look prettier?

"Grohe Sense Guard Valve" and "Grohe Sense Guard 1-day Flow" or "Main Water Valve" and "1-day Water Consumption", for example.

Looking at the code I understand that the "MY GUARD" probably comes from Grohe's API. I don't like it anyway. :)

**Comment by gkreitz** [comment]
I agree that it's ugly, but I don't think it makes sense to add a feature to overwrite it in the component, as it indeed is what the API serves up. Home assistant allows you to reconfigure entity names.
