### ISSUE TITLE
Show graph and units

### ISSUE THREAD

**Issue by trsqr** [gkreitz/homeassistant-grohe_sense#8]
Currently the counters in the UI will be shown without units and also when you click the items you cannot see historical data.

Here an example, no units (compare to my Aquarea air-water heat pump sensors for example):

![image](https://user-images.githubusercontent.com/6545027/89709346-a62cfd00-d987-11ea-8bd7-f50ffeaa651e.png)

For example, water pressure is shown like this when I click it:

![image](https://user-images.githubusercontent.com/6545027/89709956-ea200200-d987-11ea-8640-616dbac701f6.png)

Whereas I would like to see something like this:

![image](https://user-images.githubusercontent.com/6545027/89709977-06bc3a00-d988-11ea-832b-02586ca90954.png)

**Comment by gkreitz** [comment]
Thank you for this feature request!

I've now set `unit_of_measurement` on the sensor entities, which should give you the requested graphs.
